name = "aicard"
main = "src/index.ts"
compatibility_date = "2026-07-25"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "aicard-db"
database_id = "44001907-02f8-444b-8b5d-7311520da296"
migrations_dir = "migrations"
