interface Env { DB: D1Database; AI: Ai }
type CardType='person'|'opportunity'|'intelligence'|'idea';
type CardStatus='inbox'|'following'|'done'|'archived';
type CardInput={card_type?:CardType|'auto';title?:string;source_platform?:string;source_url?:string;source_text?:string;importance_reason?:string;status?:CardStatus};
const TYPES:CardType[]=['person','opportunity','intelligence','idea'];
const STATUSES:CardStatus[]=['inbox','following','done','archived'];
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const clean=(v:unknown)=>String(v??'').replace(/\s+/g,' ').trim();
const LIMITS={query:200,title:120,platform:80,url:2048,text:20000,reason:1000} as const;
const INPUT_KEYS=['card_type','title','source_platform','source_url','source_text','importance_reason','status'] as const;
const isObject=(value:unknown):value is Record<string,unknown>=>typeof value==='object'&&value!==null&&!Array.isArray(value);
const isUuid=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
function inputError(input:unknown,allowed:readonly string[]=INPUT_KEYS):string|undefined{if(!isObject(input))return'請提供 JSON 物件';for(const key of Object.keys(input))if(!allowed.includes(key))return`不支援的欄位：${key}`;for(const key of ['title','source_platform','source_url','source_text','importance_reason'])if(input[key]!==undefined&&typeof input[key]!=='string')return`${key} 必須是字串`;return undefined}
function lengthError(value:string,key:keyof typeof LIMITS,label:string){return value.length>LIMITS[key]?`${label}請控制在 ${LIMITS[key].toLocaleString('en-US')} 字內`:undefined}
function normalizeUrl(value:string):string|undefined{if(!value)return'';if(lengthError(value,'url','網址'))return undefined;try{const parsed=new URL(value);return parsed.protocol==='https:'||parsed.protocol==='http:'?parsed.toString():undefined}catch{return undefined}}
const summary=(v:string)=>clean(v).slice(0,160)||'尚未提供原始內容';
function inferType(v:string):CardType{const s=v.toLowerCase();if(/(徵求|尋找|推薦|需要|合作|報價|購買|想找|請問有沒有|商機|客戶|預約|約訪)/.test(s))return'opportunity';if(/(姓名|公司|職稱|電話|手機|email|e-mail|聯絡人|名片)/.test(s))return'person';if(/(我想到|點子|構想|如果可以|可以做成|新產品|靈感)/.test(s))return'idea';return'intelligence'}
function inferTitle(v:string){const s=clean(v);return(s.split(/[。！？!?\n]/)[0]||s).slice(0,48)||'未命名收藏'}
function inferPlatform(explicit?:string,url?:string,text?:string){const e=clean(explicit);if(e)return e;const s=(clean(url)+' '+clean(text)).toLowerCase();if(s.includes('facebook.com')||s.includes('fb.com'))return'Facebook';if(s.includes('threads.net'))return'Threads';if(s.includes('line.me')||s.includes('liff.line.me'))return'LINE';if(s.includes('youtube.com')||s.includes('youtu.be'))return'YouTube';if(s.includes('instagram.com'))return'Instagram';return'其他'}
function safeLike(v:string){return'%'+v.replace(/[\\%_]/g,'\\$&')+'%'}
async function analyze(env:Env,card:Record<string,unknown>){const type= TYPES.includes(card.card_type as CardType)?card.card_type as CardType:'intelligence';const guide:Record<CardType,string>={person:'整理人物背景、可能需求、關係切入點與下一次聯絡建議。',opportunity:'判斷需求訊號、商機強度、適合服務、自然開場方式與下一步。',intelligence:'拆解核心主張、可信度、可借鏡之處、風險與應用。',idea:'評估目標客群、痛點、最小驗證方式、收費模式與下一步。'};const prompt=`你是繁體中文的商業情報與商機顧問。${guide[type]}\n固定輸出：\n【核心判斷】\n【為何重要】\n【機會與風險】\n【下一步行動】\n\n標題：${card.title}\n來源：${card.source_platform}\n內容：${card.source_text||''}\n備註：${card.importance_reason||''}`;try{const r=await env.AI.run('@cf/meta/llama-3.1-8b-instruct',{messages:[{role:'system',content:'避免誇大與空泛鼓勵，請具體、簡潔、可執行。'},{role:'user',content:prompt}],max_tokens:800}) as{response?:string};return r.response||'分析完成，但模型沒有回傳內容。'}catch{return`【核心判斷】\n${summary(String(card.source_text||''))}\n\n【下一步行動】\n補充目標對象與用途，再決定是否追蹤。`}}
const page=`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#111827"><title>AICARD</title><style>
:root{font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;color:#172033;background:#f5f7fb;line-height:1.5}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1080px;margin:auto;padding:20px}.hero{display:flex;justify-content:space-between;gap:16px;align-items:center;margin:8px 0 20px}.hero h1{margin:0;font-size:30px}.muted{color:#64748b}.panel,.card,.stat{background:#fff;border:1px solid #e2e8f0;border-radius:18px;box-shadow:0 8px 28px rgba(15,23,42,.045)}.panel{padding:18px}.capture{margin-bottom:16px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.full{grid-column:1/-1}label{display:block;font-size:13px;font-weight:750;margin-bottom:5px}input,select,textarea{width:100%;border:1px solid #cbd5e1;border-radius:11px;padding:11px;font:inherit;background:#fff}textarea{min-height:120px;resize:vertical}.advanced{display:none;margin-top:12px}.advanced.open{display:grid}.actions{display:flex;gap:8px;justify-content:flex-end;align-items:center;margin-top:13px}.btn{border:0;border-radius:11px;padding:10px 14px;font:inherit;font-weight:750;cursor:pointer}.primary{background:#111827;color:#fff}.secondary{background:#e8edf5;color:#172033}.danger{background:#fee2e2;color:#991b1b}.ghost{background:#fff;border:1px solid #dbe3ef}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:11px;margin:16px 0}.stat{padding:13px}.stat strong{font-size:23px;display:block}.toolbar{display:flex;gap:10px;align-items:center;justify-content:space-between;margin:18px 0 11px}.tools{display:flex;gap:8px;flex-wrap:wrap}.search{min-width:240px}.cards{display:grid;gap:11px}.card{padding:16px}.top{display:flex;justify-content:space-between;gap:12px}.title{font-size:17px}.badge{font-size:12px;padding:4px 9px;border-radius:999px;background:#eef2ff;color:#3730a3;white-space:nowrap}.meta{font-size:12px;color:#64748b;margin-top:4px}.summary{margin:11px 0;line-height:1.65}.reason{border-left:3px solid #cbd5e1;padding-left:10px;color:#475569;font-size:14px}.analysis{white-space:pre-wrap;background:#f8fafc;border:1px solid #e8edf5;padding:13px;border-radius:11px;font-size:14px;margin-top:12px;line-height:1.7}.empty{text-align:center;padding:38px;color:#64748b}.loading{opacity:.6;pointer-events:none}.toast{position:fixed;left:50%;bottom:22px;transform:translateX(-50%);background:#111827;color:#fff;padding:10px 15px;border-radius:999px;display:none;z-index:50}.toast.show{display:block}.link{color:#2563eb;text-decoration:none}.status{font-size:13px;color:#64748b;margin-right:auto}@media(max-width:760px){.wrap{padding:14px}.grid{grid-template-columns:1fr}.full{grid-column:auto}.stats{grid-template-columns:1fr 1fr}.toolbar{align-items:stretch;flex-direction:column}.search{min-width:0}.hero .secondary{display:none}.card .actions{flex-wrap:wrap}}
</style></head><body><div class="wrap"><header class="hero"><div><h1>AICARD</h1><div class="muted">把看見的價值留下來，需要時再深入分析。</div></div><button class="btn secondary" onclick="loadCards()">重新整理</button></header>
<section class="panel capture" id="capture"><h2>＋ 新增收藏</h2><div class="muted">貼上文字或網址，系統會快速整理與自動分類。</div><div class="grid" style="margin-top:14px"><div class="full"><label>內容</label><textarea id="source" placeholder="貼上貼文、人物資料、商機或靈感…"></textarea></div><div><label>標題（可留空）</label><input id="title" placeholder="系統自動產生"></div><div><label>為什麼重要（可留空）</label><input id="reason" placeholder="一句話即可"></div></div><div id="advanced" class="grid advanced"><div><label>來源平台</label><input id="platform" placeholder="Facebook、Threads、LINE…"></div><div><label>分類</label><select id="type"><option value="auto">自動判斷</option><option value="opportunity">商機</option><option value="person">人物</option><option value="intelligence">情報</option><option value="idea">靈感</option></select></div><div class="full"><label>來源網址</label><input id="url" type="url" placeholder="https://…"></div></div><div class="actions"><span id="saveStatus" class="status"></span><button class="btn ghost" onclick="toggleAdvanced()">更多資訊</button><button id="saveBtn" class="btn primary" onclick="createCard()">收藏</button></div></section>
<section id="stats" class="stats"></section><div class="toolbar"><strong>卡片庫</strong><div class="tools"><input id="search" class="search" placeholder="搜尋標題、摘要或內容" oninput="debouncedLoad()"><select id="filterType" onchange="loadCards()"><option value="">全部分類</option><option value="person">人物</option><option value="opportunity">商機</option><option value="intelligence">情報</option><option value="idea">靈感</option></select><select id="filterStatus" onchange="loadCards()"><option value="">全部狀態</option><option value="inbox">收件匣</option><option value="following">跟進中</option><option value="done">已完成</option><option value="archived">已封存</option></select></div></div><main id="cards" class="cards"><div class="panel empty">正在載入…</div></main></div><div id="toast" class="toast"></div>
<script>
const E=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));const L={person:'人物',opportunity:'商機',intelligence:'情報',idea:'靈感'},I={person:'👤',opportunity:'💰',intelligence:'📚',idea:'💡'},S={inbox:'收件匣',following:'跟進中',done:'已完成',archived:'已封存'};let timer;
function toast(m){const e=document.getElementById('toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}function toggleAdvanced(){document.getElementById('advanced').classList.toggle('open')}function debouncedLoad(){clearTimeout(timer);timer=setTimeout(loadCards,300)}
async function api(path,opt){const r=await fetch(path,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'操作失敗');return d}
async function loadCards(){const q=new URLSearchParams();const search=document.getElementById('search').value.trim(),type=document.getElementById('filterType').value,status=document.getElementById('filterStatus').value;if(search)q.set('q',search);if(type)q.set('type',type);if(status)q.set('status',status);const root=document.getElementById('cards');root.innerHTML='<div class="panel empty">正在載入…</div>';try{const d=await api('/api/cards?'+q);renderStats(d.stats||{});renderCards(d.cards||[])}catch(e){root.innerHTML='<div class="panel empty">'+E(e.message)+'</div>'}}
function renderStats(s){document.getElementById('stats').innerHTML=Object.keys(L).map(k=>'<div class="stat"><strong>'+(s[k]||0)+'</strong><span>'+I[k]+' '+L[k]+'</span></div>').join('')}
function renderCards(cards){const root=document.getElementById('cards');if(!cards.length){root.innerHTML='<div class="panel empty">目前沒有符合條件的卡片</div>';return}root.innerHTML=cards.map(c=>'<article class="card" id="card-'+c.id+'"><div class="top"><div><strong class="title">'+E(c.title)+'</strong><div class="meta">'+E(c.source_platform)+' · '+E(c.created_at)+' · '+E(S[c.status]||c.status)+'</div></div><span class="badge">'+I[c.card_type]+' '+L[c.card_type]+'</span></div><div class="summary">'+E(c.summary)+'</div>'+(c.source_url?'<a class="link" href="'+E(c.source_url)+'" target="_blank" rel="noreferrer">查看來源</a>':'')+(c.importance_reason?'<div class="reason">重要原因：'+E(c.importance_reason)+'</div>':'')+'<div class="actions"><select onchange="setStatus(&quot;'+c.id+'&quot;,this.value)"><option value="inbox" '+(c.status==='inbox'?'selected':'')+'>收件匣</option><option value="following" '+(c.status==='following'?'selected':'')+'>跟進中</option><option value="done" '+(c.status==='done'?'selected':'')+'>已完成</option><option value="archived" '+(c.status==='archived'?'selected':'')+'>已封存</option></select><button class="btn secondary" onclick="doAnalyze(&quot;'+c.id+'&quot;,this)">'+(c.analysis_status==='done'?'重新分析':'深度分析')+'</button><button class="btn danger" onclick="removeCard(&quot;'+c.id+'&quot;)">刪除</button></div>'+(c.analysis_result?'<div class="analysis">'+E(c.analysis_result)+'</div>':'')+'</article>').join('')}
async function createCard(){const source=document.getElementById('source').value.trim(),url=document.getElementById('url').value.trim();if(!source&&!url){toast('請先貼上內容或網址');return}const panel=document.getElementById('capture'),btn=document.getElementById('saveBtn');panel.classList.add('loading');btn.textContent='收藏中…';try{await api('/api/cards',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({source_text:source,source_url:url,title:document.getElementById('title').value,importance_reason:document.getElementById('reason').value,source_platform:document.getElementById('platform').value,card_type:document.getElementById('type').value})});['source','url','title','reason','platform'].forEach(id=>document.getElementById(id).value='');document.getElementById('type').value='auto';toast('已收藏');await loadCards()}catch(e){toast(e.message)}finally{panel.classList.remove('loading');btn.textContent='收藏'}}
async function doAnalyze(id,btn){btn.disabled=true;btn.textContent='分析中…';try{await api('/api/cards/'+encodeURIComponent(id)+'/analyze',{method:'POST'});toast('分析完成');await loadCards();document.getElementById('card-'+id)?.scrollIntoView({behavior:'smooth',block:'center'})}catch(e){toast(e.message)}finally{btn.disabled=false}}
async function setStatus(id,status){try{await api('/api/cards/'+encodeURIComponent(id),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status})});toast('狀態已更新');loadCards()}catch(e){toast(e.message)}}
async function removeCard(id){if(!confirm('確定刪除這張卡片？'))return;try{await api('/api/cards/'+encodeURIComponent(id),{method:'DELETE'});toast('已刪除');loadCards()}catch(e){toast(e.message)}}loadCards();
</script></body></html>`;
export default{async fetch(request:Request,env:Env):Promise<Response>{const url=new URL(request.url);try{
if(request.method==='GET'&&url.pathname==='/')return new Response(page,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer'}});
if(request.method==='GET'&&url.pathname==='/api/health')return json({ok:true,service:'AICARD',version:'0.2.0'});
if(request.method==='GET'&&url.pathname==='/api/cards'){const q=clean(url.searchParams.get('q')),type=clean(url.searchParams.get('type')),status=clean(url.searchParams.get('status'));if(q.length>LIMITS.query)return json({error:`搜尋關鍵字請控制在 ${LIMITS.query} 字內`},400);if(type&&!TYPES.includes(type as CardType))return json({error:'無效的分類'},400);if(status&&!STATUSES.includes(status as CardStatus))return json({error:'無效的狀態'},400);const where:string[]=[];const binds:unknown[]=[];if(q){where.push('(title LIKE ? ESCAPE "\\" OR summary LIKE ? ESCAPE "\\" OR source_text LIKE ? ESCAPE "\\")');const like=safeLike(q);binds.push(like,like,like)}if(type){where.push('card_type = ?');binds.push(type)}if(status){where.push('status = ?');binds.push(status)}const sql='SELECT * FROM cards '+(where.length?'WHERE '+where.join(' AND '):'')+' ORDER BY created_at DESC LIMIT 200';const stmt=env.DB.prepare(sql).bind(...binds);const result=await stmt.all();const statRows=await env.DB.prepare('SELECT card_type, COUNT(*) AS count FROM cards GROUP BY card_type').all<{card_type:CardType;count:number}>();const stats=Object.fromEntries(TYPES.map(t=>[t,0]));for(const r of statRows.results)stats[r.card_type]=Number(r.count);return json({cards:result.results,stats})}
if(request.method==='POST'&&url.pathname==='/api/cards'){let raw:unknown;try{raw=await request.json()}catch{return json({error:'請提供正確的 JSON 資料'},400)}const invalid=inputError(raw);if(invalid)return json({error:invalid},400);const input=raw as CardInput;if(input.card_type!==undefined&&input.card_type!=='auto'&&!TYPES.includes(input.card_type as CardType))return json({error:'無效的分類'},400);const text=clean(input.source_text),rawUrl=clean(input.source_url),titleInput=clean(input.title),platformInput=clean(input.source_platform),reason=clean(input.importance_reason);if(!text&&!rawUrl)return json({error:'內容或網址至少填一項'},400);const tooLong=lengthError(text,'text','內容')||lengthError(titleInput,'title','標題')||lengthError(platformInput,'platform','來源平台')||lengthError(reason,'reason','重要原因');if(tooLong)return json({error:tooLong},413);const sourceUrl=normalizeUrl(rawUrl);if(sourceUrl===undefined)return json({error:'網址必須是有效的 http 或 https 網址，且不可超過 2,048 字'},400);const id=crypto.randomUUID(),combined=[text,sourceUrl,titleInput,reason].filter(Boolean).join(' '),type=input.card_type&&TYPES.includes(input.card_type as CardType)?input.card_type as CardType:inferType(combined),title=titleInput||inferTitle(text||sourceUrl),platform=inferPlatform(platformInput,sourceUrl,text);await env.DB.prepare('INSERT INTO cards (id,card_type,title,summary,source_platform,source_url,source_text,importance_reason,status) VALUES (?,?,?,?,?,?,?,?,?)').bind(id,type,title,summary(text||sourceUrl),platform,sourceUrl||null,text||null,reason||null,'inbox').run();return json({id,card_type:type},201)}
const idMatch=url.pathname.match(/^\/api\/cards\/([^/]+)$/);if(idMatch){const id=decodeURIComponent(idMatch[1]);if(!isUuid(id))return json({error:'無效的卡片 ID'},400);if(request.method==='GET'){const card=await env.DB.prepare('SELECT * FROM cards WHERE id=?').bind(id).first();return card?json({card}):json({error:'找不到卡片'},404)}if(request.method==='PATCH'){let raw:unknown;try{raw=await request.json()}catch{return json({error:'請提供正確的 JSON 資料'},400)}const invalid=inputError(raw,['status','title','importance_reason']);if(invalid)return json({error:invalid},400);const body=raw as Partial<CardInput>;if(body.status!==undefined&&!STATUSES.includes(body.status))return json({error:'無效的狀態'},400);const titleInput=body.title===undefined?undefined:clean(body.title),reason=body.importance_reason===undefined?undefined:clean(body.importance_reason);const tooLong=(titleInput===undefined?undefined:lengthError(titleInput,'title','標題'))||(reason===undefined?undefined:lengthError(reason,'reason','重要原因'));if(tooLong)return json({error:tooLong},413);const fields:string[]=[],binds:unknown[]=[];if(body.status!==undefined){fields.push('status=?');binds.push(body.status)}if(titleInput!==undefined){fields.push('title=?');binds.push(titleInput||'未命名收藏')}if(reason!==undefined){fields.push('importance_reason=?');binds.push(reason||null)}if(!fields.length)return json({error:'沒有可更新欄位'},400);fields.push('updated_at=CURRENT_TIMESTAMP');binds.push(id);const r=await env.DB.prepare('UPDATE cards SET '+fields.join(', ')+' WHERE id=?').bind(...binds).run();return r.meta.changes?json({ok:true}):json({error:'找不到卡片'},404)}if(request.method==='DELETE'){const r=await env.DB.prepare('DELETE FROM cards WHERE id=?').bind(id).run();return r.meta.changes?json({ok:true}):json({error:'找不到卡片'},404)}return json({error:'Method not allowed'},405)}
const a=url.pathname.match(/^\/api\/cards\/([^/]+)\/analyze$/);if(a){if(request.method!=='POST')return json({error:'Method not allowed'},405);const id=decodeURIComponent(a[1]);if(!isUuid(id))return json({error:'無效的卡片 ID'},400);const card=await env.DB.prepare('SELECT * FROM cards WHERE id=?').bind(id).first<Record<string,unknown>>();if(!card)return json({error:'找不到卡片'},404);await env.DB.prepare("UPDATE cards SET analysis_status='processing',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(id).run();try{const result=await analyze(env,card);await env.DB.prepare("UPDATE cards SET analysis_status='done',analysis_result=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(result,id).run();return json({analysis:result})}catch(e){await env.DB.prepare("UPDATE cards SET analysis_status='failed',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(id).run();return json({error:e instanceof Error?e.message:'分析失敗'},500)}}if(url.pathname==='/api/cards')return json({error:'Method not allowed'},405);return json({error:'Not found'},404)}catch(e){console.error(JSON.stringify({message:'request failed',path:url.pathname,error:e instanceof Error?e.message:String(e)}));return json({error:'系統錯誤'},500)}}};